export const resData = [
  {
    id: 1,
    image_url: "1.jpg",
    name: "Tasty Bites",
    location: "123 Main St, Cityville",
    cuisines: ["Italian", "Mexican"],
    average_rating: 4.5,
    lowest_price: 10.99,
    delivery_time: 30,
    contact_number: "+1 (123) 456-7890",
    website: "https://www.tastybites.com",
  },
  {
    id: 2,
    image_url: "./img/2.jpg",
    name: "Spice Fusion",
    location: "456 Elm St, Townville",
    cuisines: ["Indian", "Chinese", "Thai"],
    average_rating: 4.0,
    lowest_price: 8.99,
    delivery_time: 45,
    contact_number: "+1 (987) 654-3210",
    website: "https://www.spicefusion.com",
  },
  {
    id: 3,
    image_url: "./img/3.jpg",
    name: "Burger Junction",
    location: "789 Oak St, Villageland",
    cuisines: ["American", "Fast Food"],
    average_rating: 3.8,
    lowest_price: 6.99,
    delivery_time: 25,
    contact_number: "+1 (555) 123-4567",
    website: "https://www.burgerjunction.com",
  },
  {
    id: 4,
    image_url: "./img/4.jpg",
    name: "Sushi Palace",
    location: "567 Pine St, Sushiville",
    cuisines: ["Japanese", "Sushi"],
    average_rating: 4.6,
    lowest_price: 12.99,
    delivery_time: 35,
    contact_number: "+1 (777) 888-9999",
    website: "https://www.sushipalace.com",
  },
  {
    id: 5,
    image_url: "./img/5.jpg",
    name: "Pizza Heaven",
    location: "987 Cedar St, Pizzatown",
    cuisines: ["Italian", "Pizza"],
    average_rating: 4.4,
    lowest_price: 9.99,
    delivery_time: 30,
    contact_number: "+1 (444) 555-6666",
    website: "https://www.pizzaheaven.com",
  },
  {
    id: 6,
    image_url: "./img/6.jpg",
    name: "Noodle House",
    location: "246 Walnut St, Noodletown",
    cuisines: ["Chinese", "Asian"],
    average_rating: 4.1,
    lowest_price: 7.99,
    delivery_time: 40,
    contact_number: "+1 (222) 333-4444",
    website: "https://www.noodlehouse.com",
  },
  {
    id: 7,
    image_url: "./img/7.jpg",
    name: "BBQ Grill",
    location: "543 Oak St, BBQville",
    cuisines: ["American", "BBQ"],
    average_rating: 3.9,
    lowest_price: 11.99,
    delivery_time: 35,
    contact_number: "+1 (777) 999-8888",
    website: "https://www.bbqgrill.com",
  },
  {
    id: 8,
    image_url: "./img/8.jpg",
    name: "Mediterranean Delight",
    location: "321 Cedar St, Meditown",
    cuisines: ["Mediterranean", "Greek"],
    average_rating: 4.7,
    lowest_price: 13.99,
    delivery_time: 40,
    contact_number: "+1 (111) 222-3333",
    website: "https://www.mediterraneandelight.com",
  },
  {
    id: 9,
    image_url: "./img/9.jpg",
    name: "Thai Spice",
    location: "678 Pine St, Thaiville",
    cuisines: ["Thai"],
    average_rating: 4.2,
    lowest_price: 10.99,
    delivery_time: 30,
    contact_number: "+1 (999) 888-7777",
    website: "https://www.thaispice.com",
  },
  {
    id: 10,
    image_url: "./img/10.jpg",
    name: "Mexican Fiesta",
    location: "234 Elm St, Mexicotown",
    cuisines: ["Mexican"],
    average_rating: 3.5,
    lowest_price: 9.99,
    delivery_time: 35,
    contact_number: "+1 (666) 555-4444",
    website: "https://www.mexicanfiesta.com",
  },

  {
    id: 11,
    image_url: "https://example.com/restaurant11.jpg",
    name: "Healthy Bites",
    location: "789 Walnut St, Healthytown",
    cuisines: ["Healthy", "Salads"],
    average_rating: 3.6,
    lowest_price: 11.99,
    delivery_time: 30,
    contact_number: "+1 (888) 777-6666",
    website: "https://www.healthybites.com",
  },
  {
    id: 12,
    image_url: "https://example.com/restaurant12.jpg",
    name: "Steakhouse Grill",
    location: "567 Oak St, Steakville",
    cuisines: ["American", "Steakhouse"],
    average_rating: 4.8,
    lowest_price: 14.99,
    delivery_time: 45,
    contact_number: "+1 (777) 666-5555",
    website: "https://www.steakhousegrill.com",
  },
  {
    id: 13,
    image_url: "https://example.com/restaurant13.jpg",
    name: "Sushi Express",
    location: "432 Pine St, Sushiland",
    cuisines: ["Japanese", "Sushi"],
    average_rating: 3.3,
    lowest_price: 11.99,
    delivery_time: 35,
    contact_number: "+1 (555) 666-7777",
    website: "https://www.sushiexpress.com",
  },
  {
    id: 14,
    image_url: "https://example.com/restaurant14.jpg",
    name: "Bistro French",
    location: "876 Cedar St, Frenchville",
    cuisines: ["French"],
    average_rating: 3.5,
    lowest_price: 12.99,
    delivery_time: 40,
    contact_number: "+1 (444) 555-6666",
    website: "https://www.bistrofrench.com",
  },
  {
    id: 15,
    image_url: "https://example.com/restaurant15.jpg",
    name: "The Pasta House",
    location: "654 Walnut St, Pastatown",
    cuisines: ["Italian", "Pasta"],
    average_rating: 4.2,
    lowest_price: 9.99,
    delivery_time: 30,
    contact_number: "+1 (222) 333-4444",
    website: "https://www.thepastahouse.com",
  },
  {
    id: 16,
    image_url: "https://example.com/restaurant16.jpg",
    name: "Indian Spice",
    location: "789 Oak St, Indiatown",
    cuisines: ["Indian"],
    average_rating: 4.1,
    lowest_price: 10.99,
    delivery_time: 35,
    contact_number: "+1 (777) 888-9999",
    website: "https://www.indianspice.com",
  },
  {
    id: 17,
    image_url: "https://example.com/restaurant17.jpg",
    name: "Bakery Delights",
    location: "321 Elm St, Bakerytown",
    cuisines: ["Bakery", "Desserts"],
    average_rating: 4.4,
    lowest_price: 8.99,
    delivery_time: 25,
    contact_number: "+1 (333) 444-5555",
    website: "https://www.bakerydelights.com",
  },
  {
    id: 18,
    image_url: "https://example.com/restaurant18.jpg",
    name: "Burger Town",
    location: "567 Pine St, Burgerville",
    cuisines: ["American", "Burgers"],
    average_rating: 4.3,
    lowest_price: 9.99,
    delivery_time: 30,
    contact_number: "+1 (777) 888-9999",
    website: "https://www.burgertown.com",
  },
  {
    id: 19,
    image_url: "https://example.com/restaurant19.jpg",
    name: "Vegan Oasis",
    location: "654 Oak St, Vegantown",
    cuisines: ["Vegan", "Healthy"],
    average_rating: 4.7,
    lowest_price: 12.99,
    delivery_time: 40,
    contact_number: "+1 (555) 666-7777",
    website: "https://www.veganoasis.com",
  },
  {
    id: 20,
    image_url: "https://example.com/restaurant20.jpg",
    name: "Pizzeria Italia",
    location: "876 Elm St, Pizzaland",
    cuisines: ["Italian", "Pizza"],
    average_rating: 4.6,
    lowest_price: 11.99,
    delivery_time: 35,
    contact_number: "+1 (888) 999-0000",
    website: "https://www.pizzeriaitalia.com",
  },
];
